language: go

go:
  - 1.9

install: true

notifications:
  email: false

env:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
  - docker-compose run webhulk go test -v ./...
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet ./...
